tabWidth = 4
useTabs = false
semi = false
singleQuote = true
printWidth = 100
trailingComma = "es5"
bracketSpacing = true

plugins = [
    "prettier-plugin-jinja-template",
    #"prettier-plugin-tailwindcss"
]

[[overrides]]
files = ["*.html", "*.jinja", "**/templates/**/*.html", "**/templates/**/*.jinja"]
[overrides.options]
parser = "jinja-template"
